[project]
name = "bloxorz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kstar-planner>=1.4.16",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "tqdm>=4.67.1",
]
